// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqa6hYNf1NpTC39YJepaELuXF0jKfbrXg',
    appId: '1:687809545820:web:8d4f0a16e6948f89fa4899',
    messagingSenderId: '687809545820',
    projectId: 'blurrly',
    authDomain: 'blurrly.firebaseapp.com',
    storageBucket: 'blurrly.firebasestorage.app',
    measurementId: 'G-EVDDQ2DGS9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXcJukraMkxXVLmy0gXIp3uCkjDAmx3M',
    appId: '1:687809545820:ios:5c9257d792934b59fa4899',
    messagingSenderId: '687809545820',
    projectId: 'blurrly',
    storageBucket: 'blurrly.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqa6hYNf1NpTC39YJepaELuXF0jKfbrXg',
    appId: '1:687809545820:web:c75c12dddcbdd80dfa4899',
    messagingSenderId: '687809545820',
    projectId: 'blurrly',
    authDomain: 'blurrly.firebaseapp.com',
    storageBucket: 'blurrly.firebasestorage.app',
    measurementId: 'G-1HXP7MVQBV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXcJukraMkxXVLmy0gXIp3uCkjDAmx3M',
    appId: '1:687809545820:ios:5c9257d792934b59fa4899',
    messagingSenderId: '687809545820',
    projectId: 'blurrly',
    storageBucket: 'blurrly.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDneeOQ0FkrauEc0nOJ8y51D6zeRY06hCY',
    appId: '1:687809545820:android:8c5dca435a9cc23efa4899',
    messagingSenderId: '687809545820',
    projectId: 'blurrly',
    storageBucket: 'blurrly.firebasestorage.app',
  );

}